### ISSUE TITLE
Cannot read property 'innerWidth' of undefined

### ISSUE THREAD

**Issue by imjared** [theolampert/react-flickity-component#5]
We're consistently getting this error in our isomorphic app. Not sure if this is something you've seen but flagging anyways for future weary Googlers. Will update if I find a solution.

![image](https://cloud.githubusercontent.com/assets/525011/26652215/2241e880-461d-11e7-8dfe-5c226ecf9bb3.png)

**Comment by Abhi0725** [comment]
@imjared 
I am getting the same issue. Did you find any solution?

**Comment by theolampert** [comment]
He, I created this for use on a small project quite a while ago and haven't looked at it since. I'm not surprised it won't render server side given the way flickity works and carousels in general, it isn't possible to measure the dimensions of DOM elements server side. Honestly I'm also not sure the approach here is the best, if you're interested there is an open PR on the flickity repo itself https://github.com/metafizzy/flickity/pull/381 which has a bit more detail about the issues integrating this with react in general. Have either of you tried initialising the component only on the client?. Having said all that I'm open to suggestions or patches here.

**Comment by theolampert** [comment]
@imjared @Abhi0725 could you guys try installing from the dev branch? `npm install https://github.com/theolampert/react-flickity-component.git#dev`

**Comment by imjared** [comment]
@Abhi0725 - we ended up writing our own wrapper for flickity

**Comment by timothywisdom** [comment]
I have just found that setting the Flickity option:
watchCSS: false
makes this error go away.

**Comment by amerllica** [comment]
`Flickity` is awesome for `jQuery` or `VanillaJS`  projects, As I use it in my [`DIGIKALA MAG`](https://mag.digikala.com) project, But it is not very useful for `React` project. I unstar this repo and migrate to [`react-slick`](https://github.com/akiran/react-slick).

This awesome repo just kill my time.
