### ISSUE TITLE
flickity not found in lib error

### ISSUE THREAD

**Issue by kush-agra** [theolampert/react-flickity-component#96]
version 3.5.0 produces a webpack error and simply switching to an older version fixes it

**Comment by yaodingyd** [comment]
You need to install your own version of flickity because flickity is a peer dependency now.

**Comment by Jebble** [comment]
@yaodingyd Just want to make sure why you closed this. Installing flickity manually is an option but a component like this surely should install flickity on it's own?

**Comment by yaodingyd** [comment]
I'm not sure why it should install on it's own. Essentially it's just a very thin wrapper and giving user control of what version of flickity makes best sense for me, in this way user can upgrade flickity anytime to suit their best need instead of waiting on this component to be updated first.

**Comment by Jebble** [comment]
Well flickity doesn't really need updates if the wrapper doesn't support that version, which is why you'd make sure that the wrapper component uses the version you know works. If people then want a newer version they can simply fork this component.

It's mostly weird that suddenly flickity isn't installed with this component anymore, it's not reflected anywhere in the changelog or documentation. a minor version update shouldn't break like this. 

If you're not sure why the component should also install flickity I wonder why that was the case to begin with. Either way I've never come across packages that wrap other libraries but don't install them so I just find it a very weird practice.

**Comment by yaodingyd** [comment]
You made a very good point. I'll leave it to the owner.

**Comment by theolampert** [comment]
@Jebble Should have been a major bump sorry. Due to questions about flickity's licensing coming up in this repo quite a lot I thought it was better to have end users explicitly install the library themselves, I don't want it to appear as if I'm packaging his library for free. I'm open to it being included again and the docs being explicit about a license however.
